### ISSUE TITLE
stat_groups.find(".//span[@class='stat-title']").text is None

### ISSUE THREAD

**Issue by brliron** [Fuyukai/OWAPI#272]
## Issue

When trying to check the played heroes on my alt account, the API returns an error 500. It worked 3 days ago.
It also happened every day on another account for at least 1 month I think (but the owner of that other account stopped playing so I didn't really care).

## Links that cause the issue

`https://owapi.net/api/v3/u/HanzoShimada-21532/heroes`

## Logs
```
Jan 21 12:18:03 <hostname> node[8117]: Opening XHR on http://localhost:8080/api/v3/u/HanzoShimada-21532/stats
Jan 21 12:18:03 <hostname> pipenv[288]: 2019-01-21 12:18:03,900 - [INFO] OWAPI -> Cache miss for `_real_get_body('https://playoverwatch.com/en-us/career/pc/eu/HanzoShimada-21532',)`
Jan 21 12:18:03 <hostname> pipenv[288]: 2019-01-21 12:18:03,902 - [INFO] OWAPI -> GET => https://playoverwatch.com/en-us/career/pc/eu/HanzoShimada-21532
Jan 21 12:18:06 <hostname> pipenv[288]: 2019-01-21 12:18:06,614 - [INFO] OWAPI -> GET => https://playoverwatch.com/en-us/career/pc/eu/HanzoShimada-21532 => 200
Jan 21 12:18:06 <hostname> pipenv[288]: 2019-01-21 12:18:06,648 - [INFO] OWAPI -> Storing _real_get_body('https://playoverwatch.com/en-us/career/pc/eu/HanzoShimada-21532',) with expiration 300
Jan 21 12:18:06 <hostname> redis-server[286]: 286:M 21 Jan 2019 12:18:06.718 * 1 changes in 900 seconds. Saving...
Jan 21 12:18:06 <hostname> redis-server[286]: 286:M 21 Jan 2019 12:18:06.727 * Background saving started by pid 10141
Jan 21 12:18:06 <hostname> redis-server[286]: 10141:C 21 Jan 2019 12:18:06.753 * DB saved on disk
Jan 21 12:18:06 <hostname> redis-server[286]: 10141:C 21 Jan 2019 12:18:06.755 * RDB: 0 MB of memory used by copy-on-write
Jan 21 12:18:06 <hostname> pipenv[288]: 2019-01-21 12:18:06,822 - [INFO] Kyoukai -> GET /api/v3/u/HanzoShimada-21532/stats - 200
Jan 21 12:18:06 <hostname> node[8117]: XHR succeded.
Jan 21 12:18:06 <hostname> node[8117]: STATS successfully pushed into stats object.
Jan 21 12:18:06 <hostname> node[8117]: Opening XHR on http://localhost:8080/api/v3/u/HanzoShimada-21532/heroes
Jan 21 12:18:06 <hostname> redis-server[286]: 286:M 21 Jan 2019 12:18:06.827 * Background saving terminated with success
Jan 21 12:18:06 <hostname> pipenv[288]: 2019-01-21 12:18:06,835 - [ERROR] asyncio -> Task exception was never retrieved
Jan 21 12:18:06 <hostname> pipenv[288]: future: <Task finished coro=<KyoukaiProtocol._wait_wrapper() done, defined at /root/.local/share/virtualenvs/OWAPI-KGNxmzN7/lib/python3.6/site-packages/kyoukai/backends/httptools_.py:331> exception=CancelledError()>
Jan 21 12:18:06 <hostname> pipenv[288]: concurrent.futures._base.CancelledError
Jan 21 12:18:06 <hostname> pipenv[288]: 2019-01-21 12:18:06,842 - [INFO] OWAPI -> Cache hit for `_real_get_body('https://playoverwatch.com/en-us/career/pc/eu/HanzoShimada-21532',)`
Jan 21 12:18:07 <hostname> pipenv[288]: 2019-01-21 12:18:07,030 - [ERROR] Kyoukai -> Unhandled exception in route function
Jan 21 12:18:07 <hostname> pipenv[288]: Traceback (most recent call last):
Jan 21 12:18:07 <hostname> pipenv[288]:   File "/opt/OWAPI/owapi/v3/parsing.py", line 412, in bl_parse_hero_data
Jan 21 12:18:07 <hostname> pipenv[288]:     hbtitle = stat_groups.find(".//span[@class='stat-title']").text
Jan 21 12:18:07 <hostname> pipenv[288]: AttributeError: 'NoneType' object has no attribute 'text'
Jan 21 12:18:07 <hostname> pipenv[288]: During handling of the above exception, another exception occurred:
Jan 21 12:18:07 <hostname> pipenv[288]: Traceback (most recent call last):
Jan 21 12:18:07 <hostname> pipenv[288]:   File "/root/.local/share/virtualenvs/OWAPI-KGNxmzN7/lib/python3.6/site-packages/kyoukai/app.py", line 314, in process_request
Jan 21 12:18:07 <hostname> pipenv[288]:     result = await matched.invoke(ctx, params=params)
Jan 21 12:18:07 <hostname> pipenv[288]:   File "/root/.local/share/virtualenvs/OWAPI-KGNxmzN7/lib/python3.6/site-packages/kyoukai/route.py", line 290, in invoke
Jan 21 12:18:07 <hostname> pipenv[288]:     return await self.invoke_function(ctx, pre_hooks, post_hooks, params)
Jan 21 12:18:07 <hostname> pipenv[288]:   File "/root/.local/share/virtualenvs/OWAPI-KGNxmzN7/lib/python3.6/site-packages/kyoukai/route.py", line 151, in invoke_function
Jan 21 12:18:07 <hostname> pipenv[288]:     result = await result
Jan 21 12:18:07 <hostname> pipenv[288]:   File "/opt/OWAPI/owapi/v3/v3_util.py", line 64, in _rl_inner2
Jan 21 12:18:07 <hostname> pipenv[288]:     return await func(ctx, *args, **kwargs)
Jan 21 12:18:07 <hostname> pipenv[288]:   File "/opt/OWAPI/owapi/v3/__init__.py", line 144, in get_heroes
Jan 21 12:18:07 <hostname> pipenv[288]:     d["heroes"]["stats"]["competitive"] = parsing.bl_parse_hero_data(result, mode="competitive")
Jan 21 12:18:07 <hostname> pipenv[288]:   File "/opt/OWAPI/owapi/v3/parsing.py", line 414, in bl_parse_hero_data
Jan 21 12:18:07 <hostname> pipenv[288]:     hbtitle = stat_groups.find(".//h5[@class='stat-title']").text
Jan 21 12:18:07 <hostname> pipenv[288]: AttributeError: 'NoneType' object has no attribute 'text'
Jan 21 12:18:07 <hostname> pipenv[288]: 2019-01-21 12:18:07,032 - [ERROR] OWAPI -> Unhandled exception - Blizzard format probably changed!
Jan 21 12:18:07 <hostname> pipenv[288]: Traceback (most recent call last):
Jan 21 12:18:07 <hostname> pipenv[288]:   File "/opt/OWAPI/owapi/v3/parsing.py", line 412, in bl_parse_hero_data
Jan 21 12:18:07 <hostname> pipenv[288]:     hbtitle = stat_groups.find(".//span[@class='stat-title']").text
Jan 21 12:18:07 <hostname> pipenv[288]: AttributeError: 'NoneType' object has no attribute 'text'
Jan 21 12:18:07 <hostname> pipenv[288]: During handling of the above exception, another exception occurred:
Jan 21 12:18:07 <hostname> pipenv[288]: Traceback (most recent call last):
Jan 21 12:18:07 <hostname> pipenv[288]:   File "/root/.local/share/virtualenvs/OWAPI-KGNxmzN7/lib/python3.6/site-packages/kyoukai/app.py", line 314, in process_request
Jan 21 12:18:07 <hostname> pipenv[288]:     result = await matched.invoke(ctx, params=params)
Jan 21 12:18:07 <hostname> pipenv[288]:   File "/root/.local/share/virtualenvs/OWAPI-KGNxmzN7/lib/python3.6/site-packages/kyoukai/route.py", line 290, in invoke
Jan 21 12:18:07 <hostname> pipenv[288]:     return await self.invoke_function(ctx, pre_hooks, post_hooks, params)
Jan 21 12:18:07 <hostname> pipenv[288]:   File "/root/.local/share/virtualenvs/OWAPI-KGNxmzN7/lib/python3.6/site-packages/kyoukai/route.py", line 151, in invoke_function
Jan 21 12:18:07 <hostname> pipenv[288]:     result = await result
Jan 21 12:18:07 <hostname> pipenv[288]:   File "/opt/OWAPI/owapi/v3/v3_util.py", line 64, in _rl_inner2
Jan 21 12:18:07 <hostname> pipenv[288]:     return await func(ctx, *args, **kwargs)
Jan 21 12:18:07 <hostname> pipenv[288]:   File "/opt/OWAPI/owapi/v3/__init__.py", line 144, in get_heroes
Jan 21 12:18:07 <hostname> pipenv[288]:     d["heroes"]["stats"]["competitive"] = parsing.bl_parse_hero_data(result, mode="competitive")
Jan 21 12:18:07 <hostname> pipenv[288]:   File "/opt/OWAPI/owapi/v3/parsing.py", line 414, in bl_parse_hero_data
Jan 21 12:18:07 <hostname> pipenv[288]:     hbtitle = stat_groups.find(".//h5[@class='stat-title']").text
Jan 21 12:18:07 <hostname> pipenv[288]: AttributeError: 'NoneType' object has no attribute 'text'
Jan 21 12:18:07 <hostname> pipenv[288]: 2019-01-21 12:18:07,033 - [INFO] Kyoukai -> GET /api/v3/u/HanzoShimada-21532/heroes - 500
Jan 21 12:18:07 <hostname> node[8117]: XHR failed with status 500
```
(the `node` stats are from the bot we use to get the stats)

**Comment by relaera** [comment]
I was able to reproduce/identify the issue with this account.

https://playoverwatch.com/en-us/career/pc/HanzoShimada-21532
Click on Competitive, then click the hero-dropdown for Symmetra.

I'm getting a blank page (no stats), so there's nothing to parse. However, she's still in the list because there's recorded playtime (of zero). I'll make a branch for a graceful failure and set up a PR

**Comment by brliron** [comment]
Thanks
